### ISSUE TITLE
Remediate Vulnerability: Outdated Javascript Library

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/STNDataPortal#8]
Acunetix scan reports this app is using jQuery 1.7.2 and should be updated. This is a Medium vulnerability and should be a priority.

It reports the specific library as

>https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js

so this is probably just script tag in your HTML file that needs to be updated.

**Comment by lprivette** [comment]
@BlakeDraper This is probably hard to remember but asking incase you do... Do you remember how you ran/deployed this application? I can run it using VSCode's live thing, but the services do not work with it. there is no package.json or files to run it on a local server that I see.

![image](https://user-images.githubusercontent.com/23640741/138931036-fff784be-1326-4fe3-951e-8b54c2ed1aac.png)

**Comment by lprivette** [comment]
Resolved with https://github.com/USGS-WiM/STNDataPortal/releases/tag/v1.0.0
